### ISSUE TITLE
PHP notice when generating email report

### ISSUE THREAD

**Issue by dimadin** [easydigitaldownloads/edd-email-reports#14]
### Steps to reproduce the behavior
1) Open _Downloads_ > _Settings_ > _Emails_ > _General_. 
2) Go to _Email Report Settings_ section.
3) Click on _Preview Email Report_ button.
4) If debugging is turned on, you'll get PHP notice in a header.

You'll see the same notice in a log file when actual email report is sent.

### Information (if a specific version is affected):
EDD Version (or branch):
`release/3.0`

**Comment by dimadin** [comment]
I have found source of this bug:

https://github.com/easydigitaldownloads/edd-email-reports/blob/21c583e71d0fdcb68d0e64ccbcee547b3603990b/includes/functions.php#L282-L289

Thing is that `-1` for `number` parameter is producing notice since EDD 3.0:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/83dd85ca5f48582e255749e7844953f6d60a4090/includes/payments/class-payments-query.php#L624-L631

**Comment by robincornett** [comment]
@dimadin in cases where that number needs to be quite large, we've changed the `-1` to `9999999` or similar to bypass the notice.
